In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("../datasets/animals.csv")

In [3]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [4]:
print(X)

[[ 180    3]
 [ 190    4]
 [ 210    5]
 [ 220    5]
 [ 200    6]
 [ 210    4]
 [ 190    5]
 [ 230    6]
 [ 240    4]
 [ 250    6]
 [ 260    5]
 [ 240    7]
 [ 230    6]
 [ 220    5]
 [ 210    4]
 [ 200    3]
 [ 250    5]
 [ 260    6]
 [ 270    7]
 [ 280    6]
 [ 600   15]
 [ 620   18]
 [ 630   16]
 [ 610   17]
 [ 650   19]
 [ 670   20]
 [ 690   18]
 [ 710   19]
 [ 700   17]
 [ 720   21]
 [ 730   22]
 [ 740   23]
 [ 750   20]
 [ 760   21]
 [ 780   22]
 [ 790   23]
 [ 800   24]
 [ 810   25]
 [ 820   26]
 [ 830   27]
 [ 800   10]
 [ 820    9]
 [ 840   11]
 [ 850   10]
 [ 860    9]
 [ 870   12]
 [ 880   10]
 [ 890   11]
 [ 900   13]
 [ 910   12]
 [ 920   11]
 [ 930   13]
 [ 940   12]
 [ 950   11]
 [ 960   10]
 [ 970   12]
 [ 980   11]
 [ 990   10]
 [1000   11]
 [1010   12]
 [ 260    4]
 [ 270    3]
 [ 280    5]
 [ 290    4]
 [ 300    5]
 [ 310    6]
 [ 320    4]
 [ 330    3]
 [ 340    5]
 [ 350    6]
 [ 360    7]
 [ 370    6]
 [ 380    5]
 [ 390    4]
 [ 400    5]
 [ 840   28]
 [ 850   29]

In [5]:
print(y)

['Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog'
 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Tiger' 'Tiger' 'Tiger'
 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Tiger'
 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Lion'
 'Lion' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion'
 'Lion' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion' 'Dog'
 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog' 'Dog'
 'Dog' 'Dog' 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Tiger' 'Tiger'
 'Tiger' 'Tiger' 'Tiger' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion'
 'Lion' 'Lion' 'Lion']


In [6]:
le = LabelEncoder()
y = le.fit_transform(y)

In [7]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1]


In [8]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [9]:
print(X)

[[-1.51493726 -1.15346379]
 [-1.4826467  -1.04221602]
 [-1.41806557 -0.93096824]
 [-1.38577501 -0.93096824]
 [-1.45035613 -0.81972046]
 [-1.41806557 -1.04221602]
 [-1.4826467  -0.93096824]
 [-1.35348444 -0.81972046]
 [-1.32119388 -1.04221602]
 [-1.28890332 -0.81972046]
 [-1.25661275 -0.93096824]
 [-1.32119388 -0.70847269]
 [-1.35348444 -0.81972046]
 [-1.38577501 -0.93096824]
 [-1.41806557 -1.04221602]
 [-1.45035613 -1.15346379]
 [-1.28890332 -0.93096824]
 [-1.25661275 -0.81972046]
 [-1.22432219 -0.70847269]
 [-1.19203163 -0.81972046]
 [-0.15873361  0.18150953]
 [-0.09415248  0.51525286]
 [-0.06186192  0.29275731]
 [-0.12644305  0.40400509]
 [ 0.00271921  0.62650064]
 [ 0.06730033  0.73774842]
 [ 0.13188146  0.51525286]
 [ 0.19646258  0.62650064]
 [ 0.16417202  0.40400509]
 [ 0.22875315  0.84899619]
 [ 0.26104371  0.96024397]
 [ 0.29333427  1.07149175]
 [ 0.32562484  0.73774842]
 [ 0.3579154   0.84899619]
 [ 0.42249653  0.96024397]
 [ 0.45478709  1.07149175]
 [ 0.48707765  1.18273952]
 

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1)

In [11]:
print(X_train)

[[ 0.55165878  1.40523508]
 [ 0.9714361  -0.26348158]
 [-0.83683543 -1.04221602]
 [-1.19203163 -0.81972046]
 [ 1.32663229  0.18150953]
 [ 1.48808511  0.18150953]
 [ 0.45478709  1.07149175]
 [ 0.3579154   0.84899619]
 [ 0.80998328 -0.04098602]
 [-0.93370712 -0.70847269]
 [-1.06286938 -1.04221602]
 [ 1.00372666 -0.37472935]
 [ 0.48707765  1.18273952]
 [ 0.71311159 -0.1522338 ]
 [ 0.93914553 -0.1522338 ]
 [-0.12644305  0.40400509]
 [ 0.42249653  0.96024397]
 [ 0.80998328  2.2952173 ]
 [ 1.06830779 -0.26348158]
 [ 1.42350398  0.07026175]
 [-1.45035613 -1.15346379]
 [ 0.71311159  1.96147396]
 [ 0.55165878 -0.48597713]
 [ 1.2297606   0.07026175]
 [ 0.13188146  0.51525286]
 [ 1.45579454 -0.04098602]
 [ 0.64853047 -0.37472935]
 [ 1.16517948 -0.1522338 ]
 [-1.45035613 -0.81972046]
 [-1.09515994 -0.81972046]
 [-0.09415248  0.51525286]
 [ 0.84227385  2.40646507]
 [-1.38577501 -0.93096824]
 [-0.96599769 -0.81972046]
 [ 0.26104371  0.96024397]
 [-1.19203163 -0.93096824]
 [ 0.6162399  -0.26348158]
 

In [12]:
print(X_test)

[[ 0.48707765 -0.37472935]
 [ 0.29333427  1.07149175]
 [ 0.74540216 -0.37472935]
 [ 1.13288891 -0.26348158]
 [ 0.68082103  1.85022619]
 [ 0.84227385 -0.1522338 ]
 [ 1.26205117 -0.04098602]
 [ 0.68082103 -0.48597713]
 [ 1.29434173  0.07026175]
 [ 1.35892285  0.07026175]
 [-1.03057881 -1.15346379]
 [ 0.19646258  0.62650064]
 [-0.80454487 -0.93096824]
 [ 0.90685497  2.62896063]
 [ 0.32562484  0.73774842]
 [ 1.03601722 -0.1522338 ]
 [ 0.58394934  1.51648286]
 [-1.25661275 -0.93096824]
 [-1.41806557 -0.93096824]]


In [13]:
print(y_train)

[2 1 0 0 1 1 2 2 1 0 0 1 2 1 1 2 2 2 1 1 0 2 1 1 2 1 1 1 0 0 2 2 0 0 2 0 1
 1 1 2 2 0 0 0 0 1 1 2 0 0 0 1 0 0 2 0 2 2 0 0 2 1 2 0 0 2 0 0 0 2 0 2 0 0
 0 2]


In [14]:
print(y_test)

[1 2 1 1 2 1 1 1 1 1 0 2 0 2 2 1 2 0 0]


In [15]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [16]:
predictions = knn.predict(X_test)
decoded_predictions = le.inverse_transform(predictions)
actual_labels = le.inverse_transform(y_test)

In [17]:
# Evaluate
accuracy = accuracy_score(y_test, predictions)

In [18]:
print("✅ Accuracy:", accuracy)
print("🧠 Predicted:", decoded_predictions)
print("🎯 Actual:   ", actual_labels)

✅ Accuracy: 1.0
🧠 Predicted: ['Lion' 'Tiger' 'Lion' 'Lion' 'Tiger' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion'
 'Dog' 'Tiger' 'Dog' 'Tiger' 'Tiger' 'Lion' 'Tiger' 'Dog' 'Dog']
🎯 Actual:    ['Lion' 'Tiger' 'Lion' 'Lion' 'Tiger' 'Lion' 'Lion' 'Lion' 'Lion' 'Lion'
 'Dog' 'Tiger' 'Dog' 'Tiger' 'Tiger' 'Lion' 'Tiger' 'Dog' 'Dog']


In [19]:
# Optional: Show neighbors of the first test sample
distances, indices = knn.kneighbors([X_test[0]])
print("\n🔎 Nearest Neighbors of 1st Test Sample:")
for i in range(len(indices[0])):
    label = le.inverse_transform([y_train[indices[0][i]]])[0]
    print(f"{i+1}. Label: {label} | Distance: {distances[0][i]:.2f}")


🔎 Nearest Neighbors of 1st Test Sample:
1. Label: Lion | Distance: 0.13
2. Label: Lion | Distance: 0.16
3. Label: Lion | Distance: 0.17
